name: CI-Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
    
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.14.2
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Setup node_modules cache
        id: dependencies-cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        if: steps.dependencies-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

      - name: Run test
        run: pnpm test

      - name: Run lighthouse-ci
        run: |
          pnpm install -g @lhci/cli@0.8.x
          pnpm build
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  securityCheck:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Check for Security
        run: |
          echo "Running Security Checks... 0"
          sleep 5s;
          echo "Running Security Checks... 1"
          sleep 5s;
          echo "Running Security Checks... 2"
          sleep 5s;
          echo "Running Security Checks... 3"
